jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.14
    - continue-on-error: true
      run: python -m pip install ply && pip install six
    - continue-on-error: true
      name: Grant execute permissions
      run: chmod +x gradlew && chmod +x update-submodules && chmod +x generate-ci-auth-file
        && chmod +x scripts/check-clean-git-status
    - continue-on-error: true
      name: Set up submodules
      run: ./update-submodules
    - continue-on-error: true
      name: Generate Stone
      run: ./gradlew :core:generateStone
    - continue-on-error: true
      name: Ensure no changes in Generated Code
      run: ./scripts/check-clean-git-status
    - continue-on-error: true
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      name: Obtain oauth access token for integration tests
      run: ./generate-ci-auth-file
    - continue-on-error: true
      name: Ensure Binary Compatibility
      run: ./gradlew :core:apiCheck :android:apiCheck
    - continue-on-error: true
      name: Dependency Guard
      run: ./gradlew dependencyGuard
    - continue-on-error: true
      name: Check
      run: ./gradlew check
    - continue-on-error: true
      name: Run Integration Tests for Examples
      run: ./gradlew :examples:examples:test :examples:java:test -Pci=true --info
    - continue-on-error: true
      name: Run Integration Tests - OkHttpRequestor
      run: ./gradlew -Pcom.dropbox.test.httpRequestor=OkHttpRequestor -Pcom.dropbox.test.authInfoFile=../auth_output
        integrationTest && ./gradlew -Pcom.dropbox.test.httpRequestor=OkHttpRequestor
        -Pcom.dropbox.test.authInfoFile=../auth_output proguardTest
    - continue-on-error: true
      name: Run Integration Tests - OkHttp3Requestor
      run: ./gradlew -Pcom.dropbox.test.httpRequestor=OkHttp3Requestor -Pcom.dropbox.test.authInfoFile=../auth_output
        integrationTest && ./gradlew -Pcom.dropbox.test.httpRequestor=OkHttp3Requestor
        -Pcom.dropbox.test.authInfoFile=../auth_output proguardTest
    - continue-on-error: true
      name: Run Integration Tests - StandardHttpRequestor
      run: ./gradlew -Pcom.dropbox.test.httpRequestor=StandardHttpRequestor -Pcom.dropbox.test.authInfoFile=../auth_output
        integrationTest && ./gradlew -Pcom.dropbox.test.httpRequestor=StandardHttpRequestor
        -Pcom.dropbox.test.authInfoFile=../auth_output proguardTest
  publish:
    if: github.repository == 'dropbox/dropbox-sdk-java' && github.ref == 'refs/heads/main'
      && github.event_name != 'pull_request'
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Install JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.14
    - continue-on-error: true
      run: python -m pip install ply && pip install six
    - continue-on-error: true
      name: Grant execute permissions
      run: chmod +x gradlew && chmod +x update-submodules
    - continue-on-error: true
      name: Update submodules
      run: ./update-submodules
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD
          }}
      name: Upload Artifacts
      run: ./gradlew publishAllPublicationsToMavenCentralRepository --no-daemon --no-parallel
        --no-configuration-cache --stacktrace
    - continue-on-error: true
      name: Retrieve version
      run: 'echo "VERSION_NAME=$(cat gradle.properties | grep -w "VERSION_NAME" |
        cut -d''='' -f2)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
      if: '!endsWith(env.VERSION_NAME, ''-SNAPSHOT'')'
      name: Publish Release to Maven Central
      run: ./gradlew closeAndReleaseRepository --no-daemon --no-parallel
    - continue-on-error: true
      name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: TestReports
        path: 'core/build/reports/

          android/build/reports/

          '
    - continue-on-error: true
      name: Upload JavaDocs
      uses: actions/upload-artifact@v3
      with:
        name: JavaDocs
        path: 'core/build/docs/javadoc/

          android/build/docs/javadoc/

          '
    - continue-on-error: true
      name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BuildArtifacts
        path: 'core/build/distributions/

          android/build/distributions/

          '
name: Build, Check, Publish
on:
  repository_dispatch:
    types: trigger-ga___check.yml
